# Makefile generated by imake - do not edit!
# $XConsortium: imake.c,v 1.91 95/01/12 16:15:47 kaleb Exp $

# ----------------------------------------------------------------------
# Makefile generated from "Imake.tmpl" and </tmp/IIf.a00152>
# $XConsortium: Imake.tmpl,v 1.224.1.1 95/06/19 17:51:01 gildea Exp $
# $XFree86: xc/config/cf/Imake.tmpl,v 3.18 1995/07/12 15:27:23 dawes Exp $
#

.SUFFIXES: .i

# $XConsortium: Imake.cf,v 1.19 95/01/05 19:24:32 kaleb Exp $
# $XFree86: xc/config/cf/Imake.cf,v 3.15 1995/06/08 06:18:39 dawes Exp $

# -----------------------------------------------------------------------
# site-specific configuration parameters that need to come before
# the platform-specific parameters - edit site.def to change

# site:  $XConsortium: site.sample,v 1.9 94/04/08 17:02:06 rws Exp $
# site:  $XFree86: xc/config/cf/site.def,v 3.8 1995/05/27 01:56:50 dawes Exp $

# $XFree86: xc/config/cf/xf86site.def,v 3.48 1995/07/22 04:11:45 dawes Exp $

# -----------------------------------------------------------------------
# platform-specific configuration parameters - edit linux.cf to change

# platform:  $XConsortium: linux.cf,v 1.11 95/01/23 18:32:03 kaleb Exp $
# platform:  $XFree86: xc/config/cf/linux.cf,v 3.26 1995/07/12 15:27:34 dawes Exp $

# $XConsortium: lnxLib.rules,v 1.8 95/01/16 21:11:00 kaleb Exp $
# $XFree86: xc/config/cf/lnxLib.rules,v 3.14 1995/06/01 08:18:56 dawes Exp $

# $XConsortium: xfree86.cf,v 1.9 95/01/25 16:42:40 kaleb Exp $
# $XFree86: xc/config/cf/xfree86.cf,v 3.66 1995/07/22 04:11:47 dawes Exp $

LINKKITDIR = $(USRLIBDIR)/Server

       XF86SRC = $(SERVERSRC)/hw/xfree86
  XF86ACCELSRC = $(XF86SRC)/accel
    XF86COMSRC = $(XF86SRC)/common
 XF86CONFIGSRC = $(XF86COMSRC)
     XF86HWSRC = $(XF86SRC)/common_hw
     XF86OSSRC = $(XF86SRC)/os-support
  VGADRIVERSRC = $(XF86SRC)/vga256/drivers
VGA16DRIVERSRC = $(XF86SRC)/vga16/drivers
 VGA2DRIVERSRC = $(XF86SRC)/vga2/drivers
 MONODRIVERSRC = $(XF86SRC)/mono/drivers
   S3DRIVERSRC = $(XF86SRC)/accel/s3/drivers

        XFREE86DOCDIR = $(LIBDIR)/doc
      XFREE86PSDOCDIR = $(XFREE86DOCDIR)/PostScript
    XFREE86HTMLDOCDIR = $(XFREE86DOCDIR)/html
XFREE86JAPANESEDOCDIR = $(XFREE86DOCDIR)/Japanese

# $XConsortium: xf86.rules,v 1.7 95/01/25 16:34:39 kaleb Exp $
# $XFree86: xc/config/cf/xf86.rules,v 3.9 1995/07/12 15:27:38 dawes Exp $

# -----------------------------------------------------------------------
# site-specific configuration parameters that go after
# the platform-specific parameters - edit site.def to change

# site:  $XConsortium: site.sample,v 1.9 94/04/08 17:02:06 rws Exp $
# site:  $XFree86: xc/config/cf/site.def,v 3.8 1995/05/27 01:56:50 dawes Exp $

# -----------------------------------------------------------------------
# Imake rules for building libraries, programs, scripts, and data files
# rules:  $XConsortium: Imake.rules,v 1.197.1.1 95/06/19 18:01:48 gildea Exp $
# rules:  $XFree86: xc/config/cf/Imake.rules,v 3.18 1995/07/22 09:39:32 dawes Exp $

 _NULLCMD_ = @ echo -n

          PATHSEP = /
            SHELL = /bin/sh

              TOP = .
      CURRENT_DIR = .

            IMAKE = imake
           DEPEND = gccmakedep
        MKDIRHIER = mkdir -p
        CONFIGSRC = $(TOP)/config
         IMAKESRC = $(CONFIGSRC)/imake
        DEPENDSRC = $(CONFIGSRC)/util
           IXXSRC = $(UNSUPPORTEDSRC)/programs/ixx
              IXX = ixx
         IXXFLAGS = -s BaseObject -m TypeObj -r RequestObj -p Xf
      IXXINCLUDES = -i '<X11/Fresco/enter-scope.h>'

          INCROOT = /usr/X11R6/include
        USRLIBDIR = /usr/X11R6/lib
         SHLIBDIR = /usr/X11R6/lib
       LINTLIBDIR = $(USRLIBDIR)/lint
          MANPATH = /usr/X11R6/man
    MANSOURCEPATH = $(MANPATH)/man
           MANDIR = $(MANSOURCEPATH)1
        LIBMANDIR = $(MANSOURCEPATH)3
       FILEMANDIR = $(MANSOURCEPATH)5

               AR = ar clq
  BOOTSTRAPCFLAGS =
               CC = gcc
               AS = as

.SUFFIXES: .cxx

              CXX = g++
    CXXDEBUGFLAGS = -O2 -m486
 CXXEXTRA_DEFINES =
CXXEXTRA_INCLUDES =
  CXXIDL_INCLUDES = -I$(TOP)/include
   CXXSTD_DEFINES = -Dlinux -D__i386__ -D_POSIX_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE -DX_LOCALE
       CXXOPTIONS =
      CXXINCLUDES = $(INCLUDES) $(TOP_INCLUDES) $(CXXEXTRA_INCLUDES) $(CXXIDL_INCLUDES)
       CXXDEFINES = $(CXXINCLUDES) $(CXXSTD_DEFINES) $(THREADS_CXXDEFINES) $(CXXEXTRA_DEFINES)
         CXXFLAGS = $(CXXDEBUGFLAGS) $(CXXOPTIONS) $(THREADS_CXXFLAGS) $(CXXDEFINES)

         COMPRESS = compress
              CPP = /lib/cpp $(STD_CPP_DEFINES)
    PREPROCESSCMD = gcc -E $(STD_CPP_DEFINES)
          INSTALL = install
     INSTALLFLAGS = -c
               LD = ld
              LEX = flex -l
           LEXLIB = -lfl
             YACC = bison -y
           CCYACC = bison -y
             LINT = lint
      LINTLIBFLAG = -C
         LINTOPTS = -axz
               LN = ln -s
             MAKE = make
               MV = mv
               CP = cp

           RANLIB = ranlib
  RANLIBINSTFLAGS =

               RM = rm -f
        MANSUFFIX = 1x
     LIBMANSUFFIX = 3x
    FILEMANSUFFIX = 5x
            TROFF = psroff
         MSMACROS = -ms
              TBL = tbl
              EQN = eqn

            DVIPS = dvips
            LATEX = latex

     STD_INCLUDES =
  STD_CPP_DEFINES = -traditional -Dlinux -D__i386__ -D_POSIX_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE -DX_LOCALE
      STD_DEFINES = -Dlinux -D__i386__ -D_POSIX_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE -DX_LOCALE
 EXTRA_LOAD_FLAGS =
  EXTRA_LDOPTIONS =
  EXTRA_LIBRARIES =
             TAGS = ctags

    SHAREDCODEDEF =
         SHLIBDEF =

     SHLIBLDFLAGS =

         PICFLAGS = -B/usr/bin/jump

      CXXPICFLAGS = -B/usr/bin/jump

    PROTO_DEFINES = -DFUNCPROTO=15 -DNARROWPROTO

     INSTPGMFLAGS = -s

     INSTBINFLAGS = -m 0755
     INSTUIDFLAGS = -m 4755
     INSTLIBFLAGS = -m 0644
     INSTINCFLAGS = -m 0444
     INSTMANFLAGS = -m 0444
     INSTDATFLAGS = -m 0444
    INSTKMEMFLAGS = -m 4755

      PROJECTROOT = /usr/X11R6

     TOP_INCLUDES = -I$(INCROOT)

      CDEBUGFLAGS = -O2 -m486
        CCOPTIONS = -ansi

      ALLINCLUDES = $(INCLUDES) $(EXTRA_INCLUDES) $(TOP_INCLUDES) $(STD_INCLUDES)
       ALLDEFINES = $(ALLINCLUDES) $(STD_DEFINES) $(EXTRA_DEFINES) $(PROTO_DEFINES) $(THREADS_DEFINES) $(DEFINES)
           CFLAGS = $(CDEBUGFLAGS) $(CCOPTIONS) $(THREADS_CFLAGS) $(ALLDEFINES)
        LINTFLAGS = $(LINTOPTS) -DLINT $(ALLDEFINES) $(DEPEND_DEFINES)
         LDPRELIB = -L$(USRLIBDIR)
        LDPOSTLIB =
        LDOPTIONS = $(CDEBUGFLAGS) $(CCOPTIONS)  $(EXTRA_LDOPTIONS) $(THREADS_LDFLAGS) $(LOCAL_LDFLAGS) $(LDPRELIB)
     CXXLDOPTIONS = $(CXXDEBUGFLAGS) $(CXXOPTIONS) $(EXTRA_LDOPTIONS) $(THREADS_CXXLDFLAGS) $(LOCAL_LDFLAGS) $(LDPRELIB)

           LDLIBS = $(LDPOSTLIB) $(THREADS_LIBS) $(SYS_LIBRARIES) $(EXTRA_LIBRARIES)

           CCLINK = $(CC)

          CXXLINK = $(CXX)

     LDSTRIPFLAGS = -x
   LDCOMBINEFLAGS = -r
      DEPENDFLAGS =

        MACROFILE = linux.cf
           RM_CMD = $(RM)

    IMAKE_DEFINES =

         IRULESRC = $(CONFIGDIR)
        IMAKE_CMD = $(IMAKE) -DUseInstalled -I$(IRULESRC) $(IMAKE_DEFINES)

     ICONFIGFILES = $(IRULESRC)/Imake.tmpl $(IRULESRC)/Project.tmpl 			$(IRULESRC)/site.def $(IRULESRC)/$(MACROFILE) 			$(IRULESRC)/xfree86.cf $(IRULESRC)/xf86.rules $(IRULESRC)/xf86site.def $(IRULESRC)/host.def $(EXTRA_ICONFIGFILES)

# ----------------------------------------------------------------------
# X Window System Build Parameters and Rules
# $XConsortium: Project.tmpl,v 1.249 95/05/23 21:36:40 matt Exp $
# $XFree86: xc/config/cf/Project.tmpl,v 3.18 1995/07/22 04:11:42 dawes Exp $

# -----------------------------------------------------------------------
# X Window System make variables; these need to be coordinated with rules

           BINDIR = /usr/X11R6/bin
     BUILDINCROOT = $(TOP)
      BUILDINCDIR = $(BUILDINCROOT)/X11
      BUILDINCTOP = ..
      BUILDLIBDIR = $(TOP)/usrlib
      BUILDLIBTOP = ..
           INCDIR = $(INCROOT)/X11
           ADMDIR = /usr/adm
           LIBDIR = $(USRLIBDIR)/X11

          FONTDIR = $(LIBDIR)/fonts
         XINITDIR = $(LIBDIR)/xinit
           XDMDIR = $(LIBDIR)/xdm
           TWMDIR = $(LIBDIR)/twm
           XSMDIR = $(LIBDIR)/xsm
           NLSDIR = $(LIBDIR)/nls
       XLOCALEDIR = $(LIBDIR)/locale
        PEXAPIDIR = $(LIBDIR)/PEX
      XAPPLOADDIR = $(LIBDIR)/app-defaults
       FONTCFLAGS = -t

     INSTAPPFLAGS = $(INSTDATFLAGS)

              RGB = rgb
            FONTC = bdftopcf
        MKFONTDIR = mkfontdir

       DOCUTILSRC = $(TOP)/doc/util
       XDOCMACROS = $(DOCUTILSRC)/macros.t
       XIDXMACROS = $(DOCUTILSRC)/indexmacros.t
       PROGRAMSRC = $(TOP)/programs
           LIBSRC = $(TOP)/lib
          FONTSRC = $(TOP)/fonts
       INCLUDESRC = $(TOP)/X11
        SERVERSRC = $(TOP)/programs/Xserver
       CONTRIBSRC = $(TOP)/../contrib
   UNSUPPORTEDSRC = $(TOP)/unsupported
           DOCSRC = $(TOP)/doc
           RGBSRC = $(TOP)/programs/rgb
      BDFTOPCFSRC = $(PROGRAMSRC)/bdftopcf
     MKFONTDIRSRC = $(PROGRAMSRC)/mkfontdir
    FONTSERVERSRC = $(PROGRAMSRC)/xfs
       FONTINCSRC = $(TOP)/include/fonts
        EXTINCSRC = $(TOP)/include/extensions
     TRANSCOMMSRC = $(LIBSRC)/xtrans
   TRANS_INCLUDES = -I$(TRANSCOMMSRC)

# $XConsortium: lnxLib.tmpl,v 1.5 95/01/11 21:44:44 kaleb Exp $
# $XFree86: xc/config/cf/lnxLib.tmpl,v 3.7 1995/04/09 13:39:23 dawes Exp $

          XLIBSRC = $(LIBSRC)/X11

SOXLIBREV = 6.0
DEPXONLYLIB =
XONLYLIB =  -lX11

LINTXONLY = $(LINTLIBDIR)/llib-lX11.ln

         XLIBONLY = $(XONLYLIB)

      XEXTLIBSRC = $(LIBSRC)/Xext
   LBXXEXTLIBSRC = $(TOP)/workInProgress/lbx/lib/Xext

    XEXEXTLIBSRC = $(LIBSRC)/XExExt

SOXEXTREV = 6.0
DEPXEXTLIB =
XEXTLIB =  -lXext

LINTXEXT = $(LINTLIBDIR)/llib-lXext.ln

SOXEXTREV = 6.0
DEPLBXXEXTLIB =
LBXXEXTLIB =  -llbxXext

LINTLBXXEXT = $(LINTLIBDIR)/llib-llbxXext.ln

DEPXEXEXTLIB = $(USRLIBDIR)/libXExExt.a
XEXEXTLIB =  -lXExExt

LINTXEXEXT = $(LINTLIBDIR)/llib-lXExExt.ln

     EXTENSIONLIB = $(XEXEXTLIB) $(XEXTLIB)
  DEPEXTENSIONLIB = $(DEPXEXEXTLIB) $(DEPXEXTLIB)
    LINTEXTENSION = $(LINTXEXEXT) $(LINTXEXT)

 LINTEXTENSIONLIB = $(LINTEXTENSION)
          DEPXLIB = $(DEPEXTENSIONLIB) $(DEPXONLYLIB)
             XLIB = $(EXTENSIONLIB) $(XONLYLIB)
         LINTXLIB = $(LINTXONLYLIB)

         XAUTHSRC = $(LIBSRC)/Xau

DEPXAUTHLIB = $(USRLIBDIR)/libXau.a
XAUTHLIB =  -lXau

LINTXAUTH = $(LINTLIBDIR)/llib-lXau.ln

      XDMCPLIBSRC = $(LIBSRC)/Xdmcp

DEPXDMCPLIB = $(USRLIBDIR)/libXdmcp.a
XDMCPLIB =  -lXdmcp

LINTXDMCP = $(LINTLIBDIR)/llib-lXdmcp.ln

           XMUSRC = $(LIBSRC)/Xmu

SOXMUREV = 6.0
DEPXMULIB =
XMULIB =  -lXmu

LINTXMU = $(LINTLIBDIR)/llib-lXmu.ln

       OLDXLIBSRC = $(LIBSRC)/oldX

DEPOLDXLIB = $(USRLIBDIR)/liboldX.a
OLDXLIB =  -loldX

LINTOLDX = $(LINTLIBDIR)/llib-loldX.ln

       TOOLKITSRC = $(LIBSRC)/Xt

SOXTREV = 6.0
DEPXTOOLONLYLIB =
XTOOLONLYLIB =  -lXt

LINTXTOOLONLY = $(LINTLIBDIR)/llib-lXt.ln

      DEPXTOOLLIB = $(DEPXTOOLONLYLIB) $(DEPSMLIB) $(DEPICELIB)
         XTOOLLIB = $(XTOOLONLYLIB) $(SMLIB) $(ICELIB)
     LINTXTOOLLIB = $(LINTXTOOLONLYLIB)

       AWIDGETSRC = $(LIBSRC)/Xaw

SOXAWREV = 6.0
DEPXAWLIB =
XAWLIB =  -lXaw

LINTXAW = $(LINTLIBDIR)/llib-lXaw.ln

       XTFSRC = $(TOP)/workInProgress/Xtf

SOXTFREV = 0.7
DEPXTFLIB =
XTFLIB =  -lXtf

LINTXTF = $(LINTLIBDIR)/llib-lXtf.ln

       FRESCOSRC = $(TOP)/workInProgress/Fresco

SOFRESCOREV = 0.7
DEPFRESCOLIB =
FRESCOLIB =  -lFresco

LINTFRESCO = $(LINTLIBDIR)/llib-lFresco.ln

         XILIBSRC = $(LIBSRC)/Xi

SOXINPUTREV = 6.0
DEPXILIB =
XILIB =  -lXi

LINTXI = $(LINTLIBDIR)/llib-lXi.ln

      XTESTLIBSRC = $(LIBSRC)/Xtst

SOXTESTREV = 6.0
DEPXTESTLIB =
XTESTLIB =  -lXtst

LINTXTEST = $(LINTLIBDIR)/llib-lXtst.ln

        PEXLIBSRC = $(LIBSRC)/PEX5

SOPEXREV = 6.0
DEPPEXLIB =
PEXLIB =  -lPEX5

LINTPEX = $(LINTLIBDIR)/llib-lPEX5.ln

        XIELIBSRC = $(LIBSRC)/XIE

SOXIEREV = 6.0
DEPXIELIB =
XIELIB =  -lXIE

LINTXIE = $(LINTLIBDIR)/llib-lXIE.ln

      PHIGSLIBSRC = $(LIBSRC)/PHIGS

DEPPHIGSLIB = $(USRLIBDIR)/libphigs.a
PHIGSLIB =  -lphigs

LINTPHIGS = $(LINTLIBDIR)/llib-lphigs.ln

DEPXBSDLIB = $(USRLIBDIR)/libXbsd.a
XBSDLIB =  -lXbsd

LINTXBSD = $(LINTLIBDIR)/llib-lXbsd.ln

           ICESRC = $(LIBSRC)/ICE

SOICEREV = 6.0
DEPICELIB =
ICELIB =  -lICE

LINTICE = $(LINTLIBDIR)/llib-lICE.ln

            SMSRC = $(LIBSRC)/SM

SOSMREV = 6.0
DEPSMLIB =
SMLIB =  -lSM

LINTSM = $(LINTLIBDIR)/llib-lSM.ln

         FSLIBSRC = $(LIBSRC)/FS

DEPFSLIB = $(USRLIBDIR)/libFS.a
FSLIB =  -lFS

LINTFS = $(LINTLIBDIR)/llib-lFS.ln

         FONTLIBSRC = $(LIBSRC)/font

DEPFONTLIB = $(USRLIBDIR)/libfont.a
FONTLIB =  -lfont

LINTFONT = $(LINTLIBDIR)/llib-lfont.ln

          DEPLIBS = $(DEPXAWLIB) $(DEPXMULIB) $(DEPXTOOLLIB) $(DEPXLIB)

         DEPLIBS1 = $(DEPLIBS)
         DEPLIBS2 = $(DEPLIBS)
         DEPLIBS3 = $(DEPLIBS)

XMULIB = -lXmu $(XLIB)

        CONFIGDIR = $(LIBDIR)/config

# -----------------------------------------------------------------------
# start of Imakefile

# # Copyright (c) 1986, 1991  Stanley T. Shebs.
# # This program may be used, copied, modified, and redistributed freely
# # for noncommercial purposes, so long as this notice remains intact.

# # Imakefile created 3/18/92  Eric Ziegast

# # Lint may need option to increase working space.
# # LINTFLAGS=-ahqv

# # ******* USER-DEFINABLE OPTIONS ************************

# # This name sets the default period for xconq.  The standard period is
# # based on WWII and thus most familiar, although it lacks some realism.
# # The library includes many other periods, some variations on the stan-
# # dard period, and others that are for completely different games.
# #
# # To use another period from the lib directory, define PERIOD with its
# # name (without the ".per").  That file will be linked into the source
# # directory as "standard.c".

PERIOD=standard

# # Games usually have their manuals put in section 6 of the
# # manual pages.  Edit the suffix if necessary.

MANSUFFIX=6
MANDIR=$(MANSOURCEPATH)$(MANSUFFIX)

# # The {n,t,g,sq}roff command you use to generate ASCII docs
# # from manuscript (ms) format.

NROFF=nroff -ms

# # If you want to change any of the names, do so here

PROGRAM1=xconq
PROGRAM2=cconq
PROGRAMS=$(PROGRAM1) $(PROGRAM2)

# # XCONQLIB is where the period/map/scenario files will be installed.
# # The default is amongst other X applications libraries.

XCONQLIB=$(HOME)/lib/xconq

# # XAPPLRESDIR is where the application resource defaults are installed.
# # Normally this is in the app-defaults directory of the standard library
# # directory.  As an alternative, you may install the defaults (from
# # Xconq.ad) in your .Xdefaults file or use xrdb(1) to load them.

XAPPLRESDIR=$(XCONQLIB)
# # XAPPLRESDIR=$(XCONQLIB)   # as an alternative

# # XFONTDIR is only defined if you cannot put the fonts in the standard
# # search path and do not want to start xconq from a shell script.

# # XFONTDIR=-DXFONTDIR=\"/usr/games/lib/X11fonts/\"

# # XCONQBIN is where the XConq/Cconq/Per2C programs will be installed.
# # Normally this is (should be) the standard X bin directory.  Modify
# # if necessary.

XCONQBIN=$(HOME)/bin.sparc

# # If your system uses different curses libs, change them here

CURSESLIB=-lcurses -ltermlib

# # If your system needs strcasecmp, uncomment the definitions below.

BSD_C= # bsd.c
BSD_O= # bsd.o

# # Uncomment CRMODE if crmode() is how curses goes into raw mode.
# # (Most BSD-derived systems use cbreak() instead, as does xconq.)

CRMODE= #-DUSECRMODE

# # If your system does not have bcopy(), comment out the next line (memcpy
# # will be used instead.

BCOPY= -DBCOPY

# # If your system does not have the select() system call, comment out the
# # next line.

SELECT= -DSELECT2

# # If you're not running on a UNIX machine which can handle argc/argv
# # in the main() routing, comment out the next line

IS_UNIX=-DUNIX

# # If you want to force imake to configure for SNF fonts, uncomment
# # the line below.

USESNF= #-DSnfFonts

# # ******* STOP EDITING HERE UNLESS YOU KNOW WHAT YOU'RE DOING *******

INCLUDES = -I.
EXTRA_DEFINES = -DXCONQLIB=\"$(XCONQLIB)\" -DXAPPLRESDIR=\"$(XAPPLRESDIR)\" 	$(XFONTDIR) $(CRMODE) $(BCOPY) $(SELECT) $(IS_UNIX) $(USESNF)

# # Additional make suffixes supported by this file
.SUFFIXES: $(SUFFIXES) .ms .doc .per

# # ******* THE MAIN PROGRAM ***********************

MAINOBJS = xconq.o init.o command.o mplay.o mutil.o mproduce.o mvars.o 	sergeant.o move.o minit.o attack.o phases.o map.o mkmap.o 	side.o unit.o order.o util.o input.o help.o period.o 	ginit.o draw.o output.o standard.o $(BSD_O)

MAINSRCS = xconq.c init.c command.c mplay.c mutil.c mproduce.c mvars.c 	sergeant.c move.c minit.c attack.c phases.c map.c mkmap.c 	side.c unit.c order.c util.c input.c help.c period.c 	ginit.c draw.c output.c standard.c $(BSD_C)

# # Xconq objects
OBJS1=$(MAINOBJS) X11.o
SRCS1=$(MAINSRCS) X11.c

# # Cconq objects
OBJS2=$(MAINOBJS) curses.o
SRCS2=$(MAINSRCS) curses.c

BINDIR=$(XCONQBIN)

MATHLIB=-lm

 OBJS = $(OBJS1) $(OBJS2) $(OBJS3)
 SRCS = $(SRCS1) $(SRCS2) $(SRCS3)

all:: $(PROGRAMS)

$(PROGRAM1): $(OBJS1) $(DEPLIBS1)
	$(RM) $@
	$(CCLINK) -o $@ $(LDOPTIONS) $(OBJS1)  $(XLIB) $(LDLIBS)  $(MATHLIB) $(EXTRA_LOAD_FLAGS)

install:: $(PROGRAM1)
	@if [ -d $(DESTDIR)$(BINDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(BINDIR)); fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTPGMFLAGS)  $(PROGRAM1) $(DESTDIR)$(BINDIR)/$(PROGRAM1)

install.man:: $(PROGRAM1).man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTMANFLAGS) $(PROGRAM1).man $(DESTDIR)$(MANDIR)/$(PROGRAM1).$(MANSUFFIX)

depend::
	$(DEPEND) $(DEPENDFLAGS) -- $(ALLDEFINES) $(DEPEND_DEFINES) -- $(SRCS)

lint:
	$(LINT) $(LINTFLAGS) $(SRCS) $(LINTLIBS)
lint1:
	$(LINT) $(LINTFLAGS) $(FILE) $(LINTLIBS)

clean::
	$(RM) $(PROGRAMS)

$(PROGRAM2): $(OBJS2) $(DEPLIBS2)
	$(RM) $@
	$(CCLINK) -o $@ $(LDOPTIONS) $(OBJS2) $(CURSESLIB) $(LDLIBS)  $(EXTRA_LOAD_FLAGS)

install:: $(PROGRAM2)
	@if [ -d $(DESTDIR)$(BINDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(BINDIR)); fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTPGMFLAGS)  $(PROGRAM2) $(DESTDIR)$(BINDIR)/$(PROGRAM2)

install.man:: $(PROGRAM2).man
	@if [ -d $(DESTDIR)$(MANDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(MANDIR)); fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTMANFLAGS) $(PROGRAM2).man $(DESTDIR)$(MANDIR)/$(PROGRAM2).$(MANSUFFIX)

XAPPLOADDIR=$(XAPPLRESDIR)

install:: XConq.ad
	@if [ -d $(DESTDIR)$(XAPPLOADDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(XAPPLOADDIR)); fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTAPPFLAGS) XConq.ad $(DESTDIR)$(XAPPLOADDIR)/XConq

# # ******* DOCS ***********************

.ms.doc:
	$(NROFF) $< > $@

docs: xconq.doc xconq2.doc custom.doc period.doc

clean::
	$(RM) *.doc make.out

# # ******* PERIODS ***********************

# # Per2C objects
POBJS = per2c.o period.o

per2c:  $(POBJS)
	$(RM) $@
	$(CCLINK) -o $@ $(LDOPTIONS)  $(POBJS)  $(LDLIBS)  $(EXTRA_LOAD_FLAGS)

clean::
	$(RM) per2c

.per.c:
	$(RM) $@
	per2c < $< > $@

standard.c: per2c lib/$(PERIOD).c
	$(RM) $@
	$(LN) lib/$(PERIOD).c $@

clean::
	$(RM) standard.c lib/$(PERIOD).c

# # ******* THE LIBRARY ***********************

install:: ./lib
	@if [ -d $(XCONQLIB) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(XCONQLIB)); fi
	for i in `ls lib`; do (set -x; \
		$(INSTALL) -c $(INSTDATFLAGS) ./lib/$$i $(XCONQLIB)); done

# # ******* FONTS ***********************
# # The following definitions will install the fonts into a
# # subdirectory of the main font path.  As is, you will need
# # to use "xset +fp [installed path]" before starting xconq
# # or make a shell script to do this automatically.
# #
# # It is perhaps wiser to install the fonts manually into
# # a directory within the standard search path (for example,
# # $(FONTDIR)/misc ).  Take your pick.
# #
# # Macintosh(tm) MacX(tm) users(tm?) must copy the bdf(tm?) files to
# # their machines(tm whatever) and run the font installer(no tm, it's
# # just a dialog box(tm)) that is built into MacX(tm).

OBJS=xconq.pcf standard.pcf
FONTDIR=$(HOME)/xfonts

xconq.pcf.Z:  xconq.bdf
	$(FONTC) $(FONTCFLAGS) $? | $(COMPRESS) > $@

standard.pcf.Z:  standard.bdf
	$(FONTC) $(FONTCFLAGS) $? | $(COMPRESS) > $@

all::  $(OBJS)

all:: fonts.dir

fonts.dir:  $(OBJS)
	$(MKFONTDIR) .

clean::
	$(RM) fonts.dir

clean::
	$(RM) *.pcf *.pcf.Z

install:: $(OBJS)
	@if [ -d $(DESTDIR)$(FONTDIR)/xconq ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(FONTDIR)/xconq); fi
	@case '${MFLAGS}' in *[i]*) set +e;; esac; \
	for i in $(OBJS); do \
	(set -x; $(INSTALL) $(INSTALLFLAGS) $(INSTDATFLAGS) $$i $(DESTDIR)$(FONTDIR)/xconq); \
	done

install:: fonts.dir
	@if [ -d $(DESTDIR)$(FONTDIR)/xconq ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(FONTDIR)/xconq); fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTDATFLAGS) fonts.dir $(DESTDIR)$(FONTDIR)/xconq/fonts.dir

# # ******** MISCELLANEOUS ***********************

spotless:	clean
	$(RM) -f Makefile.* Imakefile.orig save.xconq* xconq.save *~
	(cd lib;  rm -f *.pcf *.snf fonts.dir)

archive: spotless
	(cd ..; tar cf - xconq5.5.2 | gzip > xconq5.5.2.tar.z)

# -----------------------------------------------------------------------
# common rules for all Makefiles - do not edit

.c.i:
	$(RM) $@
	$(CC) -E $(CFLAGS) $(_NOOP_) $*.c > $@

emptyrule::

clean::
	$(RM_CMD) *.CKP *.ln *.BAK *.bak *.o core errs ,* *~ *.a .emacs_* tags TAGS make.log MakeOut  "#"*

Makefile::
	-@if [ -f Makefile ]; then set -x; \
	$(RM) Makefile.bak; $(MV) Makefile Makefile.bak; \
	else exit 0; fi
	$(IMAKE_CMD) -DTOPDIR=$(TOP) -DCURDIR=$(CURRENT_DIR)

tags::
	$(TAGS) -w *.[ch]
	$(TAGS) -xw *.[ch] > TAGS

# -----------------------------------------------------------------------
# empty rules for directories that do not have SUBDIRS - do not edit

install::
	@echo "install in $(CURRENT_DIR) done"

install.man::
	@echo "install.man in $(CURRENT_DIR) done"

install.linkkit::
	@echo "install.linkkit in $(CURRENT_DIR) done"

Makefiles::

includes::

depend::

# -----------------------------------------------------------------------
# dependencies generated by makedepend

# DO NOT DELETE
xconq.o: xconq.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h map.h global.h version.h
init.o: init.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h
command.o: command.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h mplay.h
mplay.o: mplay.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h mplay.h
mutil.o: mutil.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h mplay.h
mproduce.o: mproduce.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h mplay.h
mvars.o: mvars.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h unit.h side.h mplay.h
sergeant.o: sergeant.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h
move.o: move.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h
minit.o: minit.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h mplay.h
attack.o: attack.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h map.h global.h
phases.o: phases.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h
map.o: map.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h
mkmap.o: mkmap.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h dir.h map.h
side.o: side.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h \
  /usr/lib/gcc-lib/i486-linux/2.6.3/include/limits.h \
  /usr/lib/gcc-lib/i486-linux/2.6.3/include/syslimits.h \
  /usr/include/limits.h /usr/include/posix1_lim.h \
  /usr/include/linux/limits.h
unit.o: unit.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h map.h global.h
order.o: order.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h global.h map.h
util.o: util.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h map.h
input.o: input.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h global.h map.h
help.o: help.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h map.h
period.o: period.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h
ginit.o: ginit.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h
draw.o: draw.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h map.h global.h \
  /usr/lib/gcc-lib/i486-linux/2.6.3/include/limits.h \
  /usr/lib/gcc-lib/i486-linux/2.6.3/include/syslimits.h \
  /usr/include/limits.h /usr/include/posix1_lim.h \
  /usr/include/linux/limits.h
output.o: output.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h map.h global.h
X11.o: X11.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h map.h global.h \
  /usr/X11R6/include/X11/Xos.h /usr/X11R6/include/X11/Xosdefs.h \
  /usr/include/sys/types.h /usr/include/linux/types.h \
  /usr/include/asm/types.h /usr/include/string.h \
  /usr/lib/gcc-lib/i486-linux/2.6.3/include/stddef.h /usr/include/fcntl.h \
  /usr/include/gnu/types.h /usr/include/linux/fcntl.h \
  /usr/include/asm/fcntl.h /usr/include/unistd.h /usr/include/posix_opt.h \
  /usr/include/confname.h /usr/include/sys/time.h /usr/include/linux/time.h \
  /usr/include/time.h /usr/include/signal.h /usr/include/linux/signal.h \
  /usr/include/asm/signal.h /usr/include/errno.h /usr/include/linux/errno.h \
  /usr/include/asm/errno.h /usr/X11R6/include/X11/Xlib.h \
  /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
  /usr/X11R6/include/X11/Xutil.h /usr/X11R6/include/X11/Xresource.h \
  /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Core.h \
  /usr/X11R6/include/X11/Composite.h /usr/X11R6/include/X11/Constraint.h \
  /usr/X11R6/include/X11/Object.h /usr/X11R6/include/X11/RectObj.h \
  /usr/include/sys/socket.h /usr/include/linux/socket.h \
  /usr/include/asm/socket.h /usr/include/linux/sockios.h \
  /usr/include/linux/uio.h /usr/include/netinet/in.h /usr/include/linux/in.h \
  /usr/include/asm/byteorder.h /usr/include/netdb.h /usr/include/paths.h \
  xconqlogo.icon request.h
xconq.o: xconq.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h map.h global.h version.h
init.o: init.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h
command.o: command.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h mplay.h
mplay.o: mplay.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h mplay.h
mutil.o: mutil.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h mplay.h
mproduce.o: mproduce.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h mplay.h
mvars.o: mvars.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h unit.h side.h mplay.h
sergeant.o: sergeant.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h
move.o: move.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h
minit.o: minit.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h mplay.h
attack.o: attack.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h map.h global.h
phases.o: phases.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h
map.o: map.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h
mkmap.o: mkmap.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h dir.h map.h
side.o: side.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h \
  /usr/lib/gcc-lib/i486-linux/2.6.3/include/limits.h \
  /usr/lib/gcc-lib/i486-linux/2.6.3/include/syslimits.h \
  /usr/include/limits.h /usr/include/posix1_lim.h \
  /usr/include/linux/limits.h
unit.o: unit.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h map.h global.h
order.o: order.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h global.h map.h
util.o: util.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h map.h
input.o: input.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h global.h map.h
help.o: help.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h map.h
period.o: period.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h
ginit.o: ginit.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h dir.h period.h side.h unit.h map.h global.h
draw.o: draw.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h map.h global.h \
  /usr/lib/gcc-lib/i486-linux/2.6.3/include/limits.h \
  /usr/lib/gcc-lib/i486-linux/2.6.3/include/syslimits.h \
  /usr/include/limits.h /usr/include/posix1_lim.h \
  /usr/include/linux/limits.h
output.o: output.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h side.h unit.h map.h global.h
curses.o: curses.c config.h /usr/include/stdio.h /usr/include/features.h \
  /usr/include/sys/cdefs.h /usr/include/libio.h /usr/include/_G_config.h \
  /usr/include/ctype.h misc.h period.h global.h side.h map.h \
  /usr/include/curses.h /usr/include/sys/types.h /usr/include/linux/types.h \
  /usr/include/asm/types.h /usr/include/termcap.h /usr/include/signal.h \
  /usr/include/linux/signal.h /usr/include/asm/signal.h
